<div class="card mb-12">
    <div class="card-header bg-primary text-light">
        <i class="fas fa-table"></i>
        Convênios bancários
    </div>
    <div class="card mt-2 mb-2 ml-2">
        <div class="card-body">
            <form>
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-4">
                            <div class="form-label-group">
                                <input type="text" id="firstName" class="form-control" placeholder="First name" required="required" autofocus="autofocus">
                                <label for="firstName">Cód. Convênio</label>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-label-group">
                                <input type="text" id="lastName" class="form-control" placeholder="Last name" required="required">
                                <label for="lastName">Nome convênio</label>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-label-group">
                                <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="required">
                                <label for="inputEmail">Banco</label>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <a href="#"class="btn btn-success btn-block" href="login.html">Cadastrar</a>
                        </div>
                    </div>
                </div>
        </div>

        </form>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Nome</th>
                    <th>Banco</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>123</td>
                    <td>Exemplo</td>
                    <td>Banco qualquer</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
</div>