<!DOCTYPE html>
<html lang="en">

<head>
        <base href="/localhost" />
        <meta charset="UTF-8" />
        <title><?= $title ?></title>
        <meta name="description" content="<?= $description ?>" />

        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="">

        <!-- Custom fonts for this template-->
        <link href="../public/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

        <!-- Page level plugin CSS-->
        <link href="../public/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="../public/css/sb-admin.css" rel="stylesheet">

        <link href="../public/css/style.css" rel="stylesheet">
</head>

<body id="page-top">
        <nav class="navbar navbar-expand navbar-light bg-light static-top">
                <img src="../public/img/unit-logo.png" width="60" height="30" style="margin: 0px 20px">
                <a class="navbar-brand mr-1" href="index.php">Software Programming for Work</a>
        </nav>

        <div id="wrapper">

                <!-- Sidebar -->
                <ul class="sidebar navbar-nav ">
                        <li class="nav-item active">
                                <a class="nav-link" href="remessa">
                                        <span>Remessa bancária</span>
                                </a>
                        </li>
                </ul>

                <div id="content-wrapper">
                        <div class="container-fluid">
                                <article>
                                        <?php $this->controller->renderView(); ?>
                                </article>
                        </div>
                        <!-- /.content-wrapper -->
                </div>
                <!-- /#wrapper -->


                <!-- Bootstrap core JavaScript-->
                <script src="../public/vendor/jquery/jquery.min.js"></script>
                <script src="../public/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

                <!-- Core plugin JavaScript-->
                <script src="../public/vendor/jquery-easing/jquery.easing.min.js"></script>

                <!-- Page level plugin JavaScript-->
                <script src="../public/vendor/chart.js/Chart.min.js"></script>
                <script src="../public/vendor/datatables/jquery.dataTables.js"></script>
                <script src="../public/vendor/datatables/dataTables.bootstrap4.js"></script>

                <!-- Custom scripts for all pages-->
                <script src="../public/js/sb-admin.min.js"></script>


</body>


</html>