<!DOCTYPE html>
<html lang="en">
        <head>
                <base href="/localhost" />
                <meta charset="UTF-8" />
                <title><?= $title ?></title>
                <meta name="description" content="<?= $description ?>" />
                <link rel="stylesheet" href="../public/css/style.css" type="text/css"/>
        </head>

        <body>
                <header>
                        <h1>Instrodução à programação - UNIT</h1>
                </header>

                <nav>
                        <ul>
                                <li><a href="article/home">Software</a></li>
                                <li><a href="article">Programmimg</a></li>
                                <li><a href="contact">for Work</a></li>
                        </ul>
                </nav>
                <br clear="both" />

                <article>

                </article>

                <footer>
                        <p><a href="https://github.com/alvesmog/unit-spw-1" target="_blank">Github do projeto</a> - Guilherme Augusto Alves.</p>
                </footer>
        </body>
</html>