<div class="card mb-12">
    <div class="card-header text-dark" style="background-color: rgb(153, 232, 175);">
        <i class="fas fa-table"></i>
        <b>Remessas bancárias</b>
    </div>

    <div class="card mt-2 mb-2 ml-2 mr-2">
        <div class="card-body col-lg-12 col-md-12">
            <form>
                <div class="form-group">
                    <label for="nomeDoArquivo"><b>Nome do arquivo</b></label>
                    <div class="form-row">

                        <div class="input-group col-lg-4 col-md-4">
                            <input type="text" id="nomeDoArquivo" class="form-control" required="required" autofocus="autofocus">
                        </div>

                        <div class="input-group col-lg-3 col-md-3">
                            <select id="convenio" class="form-control" required="required">
                            </select>
                            <span class="input-group-btn">
                                <a href="cadastrarconvenio">
                                    <i class="fas fa-plus-circle fa-2x" height="20" width="20"></i>
                                </a>
                            </span>
                        </div>

                        <div class="col">
                            <a href="remessa" class="btn btn-primary btn-block" href="login.html">Processar</a>
                        </div>
                        
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Position</th>
                    <th>Office</th>
                    <th>Age</th>
                    <th>Start date</th>
                    <th>Salary</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Position</th>
                    <th>Office</th>
                    <th>Age</th>
                    <th>Start date</th>
                    <th>Salary</th>
                </tr>
            </tfoot>
            <tbody>
                <tr>
                    <td>Tiger Nixon</td>
                    <td>System Architect</td>
                    <td>Edinburgh</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>$320,800</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
</div>