<div class="card mb-12">
    <div class="card-header bg-primary text-light">
        <i class="fas fa-table"></i>
        Remessas bancárias
    </div>
    <div class="card mt-2 mb-2 ml-2">
        <div class="card-body">
            <form>
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-4">
                            <div class="form-label-group">
                                <label for="nomeDoArquivo">Nome do arquivo</label>
                                <input type="text" id="nomeDoArquivo" class="form-control" required="required" autofocus="autofocus">
                            </div>
                        </div>
                        <div class="col-md-4">

                        </div>
                        <div class="col-md-2">
                            <div class="form-label-group">
                                <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="required">
                                <label for="inputEmail">Convênio</label>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <a href="cadastrarconvenio">
                                <i class="fas fa-plus-circle fa-2x" height="20" width="20"></i>
                            </a>
                        </div>
                        <div class="col-md-1">
                            <a href="remessa" class="btn btn-primary btn-block" href="login.html">Processar</a>
                        </div>
                    </div>
                </div>
        </div>

        </form>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Position</th>
                    <th>Office</th>
                    <th>Age</th>
                    <th>Start date</th>
                    <th>Salary</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Position</th>
                    <th>Office</th>
                    <th>Age</th>
                    <th>Start date</th>
                    <th>Salary</th>
                </tr>
            </tfoot>
            <tbody>
                <tr>
                    <td>Tiger Nixon</td>
                    <td>System Architect</td>
                    <td>Edinburgh</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>$320,800</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
</div>